### PR TITLE
add API documentation

### LINKED ISSUE #1: add doxygen documentation
add all documentation from http://maemo.org/api_refs/5.0/5.0-final/icd2/index.html

### PR DESCRIPTION
**Pull request by spinal84**
Closes #1

### CODE REVIEW

**Comment by MerlijnWajer** [comment]
Should the (generated) html files be in the repo? Otherwise - nice work!

@freemangordon - any comments?

**Comment by spinal84** [comment]
Only if we want the parser to be in the repository. Do we?

**Comment by freemangordon** [comment]
I don't get it why we need the parser in the repo if we remove the generated html files. doxygen will build them for us when the packages are build, unless I miss something.

**Comment by spinal84** [comment]
It gives the stats on missing things, so if you gonna to add more RE things it could be helpful.
I'm going to add it in a while, so you could try and judge if we need it in the tree.

**Comment by MerlijnWajer** [comment]
I think it would be good to have the parser script somewhere, either in this repo or in some utils/tools repo, but I think that we don't need the generated html files if we have the source in the repo. :)

**Comment by freemangordon** [comment]
For sure we want the parser script somewhere, utils/tools repo sounds like the right place for it

**Pull request closed without merging**
